In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("data\\house-prices.csv")
df.head()

    Price    SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0  114300  1790.0       2.0        2.0     2.0    No         East
1  114200  2030.0       4.0        2.0     3.0    No         East
2  114800  1740.0       3.0        2.0     1.0    No         East
3   94700  1980.0       3.0        2.0     3.0    No         East
4  119800  2130.0       3.0        3.0     3.0    No         East

## (پیش پردازش)

شالان که دیتاست آپلود شد باید پیش پردازش کنیم
######
یعنی دیتاست را برای train تمیز کنیم

In [12]:
print("="*50)
print("INFO DATAFRAME")
print("="*50)
print(df.info())

print("\n" + "="*50)
print("DESCRIBE (آمار توصیفی)")
print("="*50)
print(df.describe(include='all'))

print("\n" + "="*50)
print("تعداد مقادیر NULL در هر ستون")
print("="*50)
print(df.isna().sum())

==================================================
INFO DATAFRAME
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Price         128 non-null    int64
 1   SqFt          126 non-null    float64
 2   Bedrooms      125 non-null    float64
 3   Bathrooms     127 non-null    float64
 4   Offers        126 non-null    float64
 5   Brick         128 non-null    object
 6   Neighborhood  128 non-null    object
dtypes: float64(4), int64(1), object(2)
memory usage: 7.1+ KB
None

==================================================
DESCRIBE (آمار توصیفی)
==================================================
                Price         SqFt    Bedrooms   Bathrooms      Offers Brick  \
count      128.000000   126.000000  125.000000  127.000000  126.000000   128
unique            NaN          NaN         NaN         NaN         NaN     2
top               NaN          NaN         NaN         NaN         NaN    No
freq              NaN          NaN         NaN         NaN         NaN    86
mean    130427.343750  2001.666667    3.032000    2.448819    2.563492   NaN
std      26868.770371   212.387382    0.728852    0.514992    1.069550   NaN
min      69100.000000  1450.000000    2.000000    2.000000    1.000000   NaN
25%     111325.000000  1882.500000    3.000000    2.000000    2.000000   NaN
50%     125950.000000  2000.000000    3.000000    2.000000    3.000000   NaN
75%     148250.000000  2140.000000    3.000000    3.000000    3.000000   NaN
max     211200.000000  2590.000000    5.000000    4.000000    6.000000   NaN

       Neighborhood
count           128
unique            3
top            East
freq             45
mean            NaN
std             NaN
min             NaN
25%             NaN
50%             NaN
75%             NaN
max             NaN

==================================================
تعداد مقادیر NULL در هر ستون
==================================================
Price           0
SqFt            2
Bedrooms        3
Bathrooms       1
Offers          2
Brick           0
Neighborhood    0
dtype: int64

تابع info:

با استفاده از این تابع جزییات کامل دیتاست را اعم از تایپ و تعداد مقادیر غیر خالی هر ویژگی
######
تابع describe:

این تابع جزییات کامل آمار توصیفی اعم از میانه و میانگین و واریانس و چارک های داده های عددی و فراوانی و داده های غیر عددی
######
تابع isna:

این تابع تعداد سلول های خالی هر ویژگی را نمایش میدهد

با استفاده از عدد واریانس میتوان دید که آیا دیتا ست ما داده های پرت زیادی دارد یا نه

اگر واریانس به 0 نزدیک باشد میتوانیم بگوییم که داده پرت زیادی ندارد
###### ----------------------------------------
برای پر کردن سلول های خالی بهتر

برای ویژگی های پیوسته به واریانس نگاه میکنیم اگر واریانس زیاد باشد بهتر است از میانه استفاده کنیم

اما اگر واریانس نزدیک به صفر باشد از میانگین استفاده میکنیم

اما به طور قطع نمیتوان با واریانس فراوانی داده های پرت را حساب کرد

پس از  IQR برای احتساب این مقادیر استفاده میکنیم

برای داده های پیوسته ویانگین و واریانس معنایی ندارد

برای این ویژگی ها یا از مد استفاده میکنیم یا از میانه

بهتر هست که از میانه استفاده کنیم
###### ----------------------------------------
برای داده پر کردن سلول های غیر عددی

تنها راه حل استفاده از مد یا همان فراوانی هست که کم ریسک ترین راه حل هست

In [13]:
X = df[['SqFt', 'Bedrooms', 'Bathrooms', 'Offers', 'Brick', 'Neighborhood']]
y = df['Price']
X.head()

     SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0  1790.0       2.0        2.0     2.0    No         East
1  2030.0       4.0        2.0     3.0    No         East
2  1740.0       3.0        2.0     1.0    No         East
3  1980.0       3.0        2.0     3.0    No         East
4  2130.0       3.0        3.0     3.0    No         East

In [17]:
col = "SqFt"

Q1 = X[col].quantile(0.25)
Q3 = X[col].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = X[(X[col] < lower_bound) | (X[col] > upper_bound)]
print(f"\n{col}: {len(outliers)} داده پرت")

SqFt: 3 داده پرت

داده هایی که بیشتر از Q3 + 1.5 * IQR باشند

یا کمتر از Q1 - 1.5 * IQR باشند

داده های پرت محسوب میشوند

اما برای داده های پیوسته حساب میکنیم

چون برای پر کردن سلول های خالی ویژگی های گسسته از میانه استفاده میکنیم.

به دلیل وجود داده های پرت بهتر است برای ویژگی های پیوسته هم از میانه استفاده کنیم

In [20]:
numeric_cols = ['SqFt', 'Bedrooms', 'Bathrooms', 'Offers']

for col in numeric_cols:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)

print(df.isna().sum())

Price           0
SqFt            0
Bedrooms        0
Bathrooms       0
Offers          0
Brick           0
Neighborhood    0
dtype: int64

پس تمام سلول های خالی را با میانه پر کردیم